<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ros2_vg10_gripper</name>
  <version>0.0.1</version>
  <description>Basic ROS2 Support for the OnRobot VG10 Gripper with a UR Robot</description>
  <maintainer email="eyy@umich.edu">Elvin Yang</maintainer>
  <license>BSD-3-Clause</license>

  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
